// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $index from "./routes/index.tsx";
import * as $items_dateISO_edit from "./routes/items/[dateISO]/edit.tsx";
import * as $items_dateISO_index from "./routes/items/[dateISO]/index.tsx";
import * as $items_index from "./routes/items/index.ts";
import * as $login_index from "./routes/login/index.tsx";
import * as $logout_index from "./routes/logout/index.ts";
import * as $DeleteButton from "./islands/DeleteButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/index.tsx": $index,
    "./routes/items/[dateISO]/edit.tsx": $items_dateISO_edit,
    "./routes/items/[dateISO]/index.tsx": $items_dateISO_index,
    "./routes/items/index.ts": $items_index,
    "./routes/login/index.tsx": $login_index,
    "./routes/logout/index.ts": $logout_index,
  },
  islands: {
    "./islands/DeleteButton.tsx": $DeleteButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
